version: "3.8"

services:
	mariadb:
		build: ./requirements/mariadb
		container_name: srcs-mariadb-1
		restart: unless-stopped
		networks: [inception]
		volumes:
			- srcs_db_data:/var/lib/mysql
			- ../secrets:/run/secrets:ro
		environment:
			DB_NAME: wordpress
			DB_USER: wpuser
			DB_HOST: mariadb
		expose:
			- "3306"

	wordpress:
		build: ./requirements/wordpress
		container_name: srcs-wordpress-1
		restart: unless-stopped
		depends_on: [mariadb]
		networks: [inception]
		volumes:
			- srcs_wp_data:/var/www/html
			- ../secrets:/run/secrets:ro
		environment:
			DB_NAME: wordpress
			DB_USER: wpuser
			DB_HOST: mariadb:3306
		expose:
			- "9000"

	nginx:
		build: ./requirements/nginx
		container_name: srcs-nginx-1
		restart: unless-stopped
		depends_on: [wordpress]
		networks: [inception]
		ports:
			- "443:443"
		volumes:
			- srcs_wp_data:/var/www/html

networks:
	inception:
		driver: bridge

volumes:
	srcs_wp_data:
		driver: local
		driver_opts:
			type: none
			o: bind
			device: ../data/wordpress
	srcs_db_data:
		driver: local
		driver_opts:
			type: none
			o: bind
			device: ../data/mariadb
